name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
    # Only publish when this publish-to-comfy_org branch is pushed
      - publish-to-comfy_org
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    # if this is a forked repository, skip this workflow.
    if: github.event.repository.fork == false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "publish-to-comfy_org"
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          ## Add your own personal access token to your Github Repository secrets and reference it here.
          personal_access_token: ${{ secrets.COMFY_NODE_SCRECRET_00 }}
